/**
 * Client handler registry logic for fabricPlugin.
 *
 * Glob-discovers handler files, then writes two generated modules:
 *   - `src/.generated/handlers.ts` — imports every `*Handler` and calls
 *     `register(...)`; no handler paths live in source.
 *   - `src/.generated/client-entry.ts` — the module the browser loads; it
 *     imports the handlers module (side-effect registration) and re-exports
 *     the framework's hydration functions. No project entry file is needed.
 */

import { glob } from "tinyglobby";
import { resolve, relative, dirname } from "node:path";
import { writeFileSync, mkdirSync } from "node:fs";

export interface HandlersOptions {
  /**
   * Glob pattern(s) (relative to project root) that match handler files
   * to auto-register. Each matched file is expected to export one or more
   * classes whose names end in `Handler` (e.g. `DismissHandler`); those
   * classes are registered with the hydration runtime automatically.
   *
   * @default ["src/views/handlers/**\/*.ts"]
   */
  include?: string | string[];

  /**
   * Optional glob pattern(s) to exclude from `include`.
   * @default []
   */
  exclude?: string | string[];

  /**
   * Output path (relative to project root or absolute) for the generated
   * registration module. Regenerated on every build and whenever a
   * matching handler file is added/removed during dev.
   *
   * @default "src/.generated/handlers.ts"
   */
  outfile?: string;

  /**
   * Output path (relative to project root or absolute) for the generated
   * client entry module. This is the module the browser loads; it imports
   * the generated registration module (side-effect) and re-exports the
   * framework's hydration functions (`hydrate` / `hydrateEvent`). Its
   * existence removes the need for a hand-written project entry file.
   *
   * @default "src/.generated/client-entry.ts"
   */
  entryOutfile?: string;

  /**
   * Extra leading comment lines placed at the top of the generated module
   * to help developers orient (they are regenerated, so keep them short).
   * @default []
   */
  header?: string[];
}

export interface ResolvedHandlersPaths {
  projectRoot: string;
  include: string[];
  exclude: string[];
  outfile: string;
  entryOutfile: string;
  header: string[];
}

export function resolveHandlersPaths(
  projectRoot: string,
  options: HandlersOptions = {},
): ResolvedHandlersPaths {
  const toAbsolute = (p: string | undefined, fallback: string) =>
    p && p.startsWith("/") ? p : resolve(projectRoot, p ?? fallback);

  const asArray = (v: string | string[] | undefined) =>
    v === undefined ? [] : Array.isArray(v) ? v : [v];

  const include = asArray(options.include);
  if (include.length === 0) {
    include.push("src/views/handlers/**/*.ts");
  }

  return {
    projectRoot,
    include,
    exclude: asArray(options.exclude),
    outfile: toAbsolute(options.outfile, "src/.generated/handlers.ts"),
    entryOutfile: toAbsolute(
      options.entryOutfile,
      "src/.generated/client-entry.ts",
    ),
    header: options.header ?? [],
  };
}

/**
 * Discover handler files matched by the configured glob, resolved to
 * absolute paths, sorted for stable output.
 */
export async function discover(
  paths: ResolvedHandlersPaths,
): Promise<string[]> {
  let files = await glob(paths.include, {
    ignore: paths.exclude.length > 0 ? paths.exclude : undefined,
    dot: false,
    absolute: true,
  });
  files = files
    .filter((f) => f !== paths.outfile)
    .sort((a, b) => a.localeCompare(b));
  return files;
}

/**
 * Generate the registration module that imports every discovered handler
 * and registers each exported `*Handler` class with the hydration runtime.
 *
 * Discovery is driven by a configurable glob (see `include`), so handler
 * files never need to be enumerated by hand. Registration is derived from
 * the exported class name at runtime (BaseHandler.handlerName), not wired
 * here — this module just imports and registers them.
 */
function generateModule(paths: ResolvedHandlersPaths, files: string[]): string {
  const outDir = dirname(paths.outfile);

  const lines: string[] = [];
  lines.push("// AUTO-GENERATED by fabricPlugin — do not edit.");
  for (const line of paths.header) {
    lines.push(`// ${line}`);
  }
  lines.push("");
  lines.push('import { register } from "spindlework/fabric";');
  lines.push("");

  files.forEach((file, index) => {
    const rel = relative(outDir, file).replace(/\\/g, "/");
    const spec = rel.startsWith(".") ? rel : `./${rel}`;
    lines.push(`import * as H${index} from "${spec}";`);
  });

  if (files.length > 0) {
    lines.push("");
    lines.push("for (const mod of [");
    files.forEach((_, index) => lines.push(`  H${index},`));
    lines.push("]) {");
    lines.push('  for (const key of Object.keys(mod)) {');
    lines.push('    if (key.endsWith("Handler")) {');
    lines.push("      register((mod as any)[key]);");
    lines.push("    }");
    lines.push("  }");
    lines.push("}");
  }

  lines.push("");
  return lines.join("\n");
}

/**
 * Generate the client entry module — the module the browser actually loads.
 *
 * It imports the generated registration module (side-effect: registers every
 * discovered handler) and re-exports the framework's hydration functions.
 * Being generated removes the need for a hand-written project entry file.
 */
function generateClientEntry(paths: ResolvedHandlersPaths): string {
  const handlersSpec = relative(
    dirname(paths.entryOutfile),
    paths.outfile,
  ).replace(/\\/g, "/");
  const rel = handlersSpec.startsWith(".") ? handlersSpec : `./${handlersSpec}`;

  const lines: string[] = [];
  lines.push("// AUTO-GENERATED by fabricPlugin — do not edit.");
  for (const line of paths.header) {
    lines.push(`// ${line}`);
  }
  lines.push("");
  lines.push('import { hydrate, hydrateEvent } from "spindlework/fabric";');
  lines.push(`import ${JSON.stringify(rel)};`);
  lines.push("");
  lines.push("export { hydrate, hydrateEvent };");
  lines.push("");
  return lines.join("\n");
}

/** Write both generated modules for the discovered handler files. */
export function writeHandlerModules(
  paths: ResolvedHandlersPaths,
  files: string[],
): void {
  mkdirSync(dirname(paths.outfile), { recursive: true });
  writeFileSync(paths.outfile, generateModule(paths, files), "utf-8");

  mkdirSync(dirname(paths.entryOutfile), { recursive: true });
  writeFileSync(
    paths.entryOutfile,
    generateClientEntry(paths),
    "utf-8",
  );

  console.log(
    `🔌 Registered ${files.length} client handler${files.length === 1 ? "" : "s"}`,
  );
}

/**
 * Absolute directory roots of the include globs (the part before the first
 * glob metacharacter). Used for dev watching and as a fast-path check when
 * deciding whether an add/unlink event should trigger regeneration.
 */
export function includeRoots(paths: ResolvedHandlersPaths): string[] {
  const roots = new Set<string>();
  for (const pattern of paths.include) {
    const root = pattern.replace(/\\/g, "/").split(/[*{]/)[0];
    if (root === "") continue;
    roots.add(
      root.startsWith("/")
        ? root
        : resolve(paths.projectRoot, root).replace(/\\/g, "/"),
    );
  }
  return [...roots];
}

/** True if `file` (absolute) is governed by the include globs. */
export function isUnderInclude(paths: ResolvedHandlersPaths, file: string): boolean {
  const norm = file.replace(/\\/g, "/");
  return includeRoots(paths).some((abs) => norm.startsWith(abs));
}