/**
 * Seed compilation helpers for fiberPlugin.
 *
 *   src/domains/seed.ts  →  src/.generated/seed.ts  (rows + hash — no faker)
 *
 * The faker library is only ever imported by this process (the project's
 * devDependency); the emitted module is plain row data, so the worker bundle
 * stays faker-free.
 */

import { dirname, join } from "path";
import { createHash } from "node:crypto";
import { writeFile, mkdir, unlink, rename } from "node:fs/promises";
import { build as esbuild } from "esbuild";
import { pathToFileURL } from "node:url";
import { tmpdir } from "node:os";
import { compileSeed, type SeedSpec } from "../src/seed";
import type { ResolvedFiberPaths } from "./options";

/**
 * Bundle the seed spec and execute it for the SeedSpec.
 *
 * The spec imports the generated runtime schema module (written first by the
 * fiber pipeline) by its on-disk relative path — alias that to the actual
 * generated file so bundling resolves it.
 */
export async function loadSeedSpec(
  projectRoot: string,
  seedPath: string,
  runtimeSchemaPath: string,
): Promise<SeedSpec> {
  const result = await esbuild({
    entryPoints: [seedPath],
    bundle: true,
    write: false,
    format: "esm",
    platform: "node",
    plugins: [
      {
        name: "spindlework-generated-schema-alias",
        setup(build) {
          build.onResolve({ filter: /\.generated\/schema(\.ts)?$/ }, (args) => {
            if (args.importer?.startsWith(projectRoot)) {
              return { path: runtimeSchemaPath };
            }
            return undefined;
          });
        },
      },
    ],
  });

  const code = result.outputFiles[0].text;
  const tmpFile = join(
    tmpdir(),
    `spindlework-seed-${createHash("sha1").update(seedPath).digest("hex").slice(0, 12)}-${Date.now()}.mjs`,
  );
  await writeFile(tmpFile, code, "utf-8");
  try {
    const mod = (await import(pathToFileURL(tmpFile).href)) as {
      seed: SeedSpec;
    };
    return mod.seed;
  } finally {
    await unlink(tmpFile).catch(() => {});
  }
}

/** Table name → literal `rows()` from the seed spec (checkRef union sources). */
export async function loadSeedLookups(
  paths: ResolvedFiberPaths,
): Promise<Map<string, Record<string, unknown>[]>> {
  const lookups = new Map<string, Record<string, unknown>[]>();
  try {
    const seed = await loadSeedSpec(
      paths.projectRoot,
      paths.seedPath,
      paths.runtimeSchemaPath,
    );
    for (const [table, spec] of Object.entries(seed.tables)) {
      if ("rows" in spec) lookups.set(table, spec.rows);
    }
  } catch {
    console.warn(
      "⚠ fiberPlugin: no seed spec loaded — checkRef columns fall back to their base type",
    );
  }
  return lookups;
}

/** Compile the seed spec into the pure-data runtime module. */
export async function generateSeedOutput(
  paths: ResolvedFiberPaths,
): Promise<void> {
  const spec = await loadSeedSpec(
    paths.projectRoot,
    paths.seedPath,
    paths.runtimeSchemaPath,
  );
  const compiled = compileSeed(spec);

  const header = `// AUTO-GENERATED by spindlework/fiber — do not edit\n// Source of truth: src/domains/seed.ts\n\n`;
  const content = `${header}import type { CompiledSeed } from "spindlework/fiber";\n\nexport const seedDef: CompiledSeed = ${JSON.stringify(compiled, null, 2)};\n`;

  await mkdir(dirname(paths.runtimeSeedPath), { recursive: true });
  // Unique temp name: concurrent generators (e.g. a running dev server and a
  // build/test run) can collide on a fixed `.tmp` path. Last writer wins on
  // the final rename, which is safe — content is identical or newer.
  const tmpPath = `${paths.runtimeSeedPath}.tmp-${process.pid}-${Date.now()}`;
  await writeFile(tmpPath, content, "utf-8");
  await rename(tmpPath, paths.runtimeSeedPath);
}