/**
 * Generate TypeScript model interfaces from a SchemaDef.
 *
 * Emits a `.d.ts` file with:
 * - One interface per table (PascalCase singular name, e.g., `tenets` → `Tenet`)
 * - A `Database` interface mapping table names to their row types
 * - A `declare module "*.sql"` block for SQL file imports
 *
 * This replaces the old SQL-parse→types path: types are now derived directly
 * from the TypeScript schema definition.
 */

import { ColumnDef } from "./column";
import type { SchemaDef, SqliteType } from "./schema";

/** Convert a table name to PascalCase singular form (same rules as before). */
export function tableNameToTypeName(
  tableName: string,
  overrides: Record<string, string> = {},
): string {
  if (overrides[tableName]) return overrides[tableName];

  const pascalCase = tableName
    .split("_")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");

  return singularize(pascalCase);
}

/** Simple singularization for English words (ported from the SQL typegen). */
function singularize(word: string): string {
  if (word.endsWith("ss") || word.endsWith("us") || word.endsWith("is")) {
    return word;
  }
  if (word.endsWith("ies")) return word.slice(0, -3) + "y";
  if (word.endsWith("ives")) return word.slice(0, -4) + "ife";
  if (word.endsWith("ves")) return word.slice(0, -3) + "f";
  if (word.endsWith("sses")) return word.slice(0, -2);
  if (
    word.endsWith("ses") ||
    word.endsWith("xes") ||
    word.endsWith("zes") ||
    word.endsWith("ches") ||
    word.endsWith("shes")
  ) {
    return word.slice(0, -2);
  }
  if (word.endsWith("oes")) return word.slice(0, -2);
  if (word.endsWith("s")) return word.slice(0, -1);
  return word;
}

/** Map SQLite column types to TypeScript types. */
function sqliteTypeToTs(sqliteType: SqliteType): string {
  switch (sqliteType) {
    case "INTEGER":
      return "number";
    case "TEXT":
      return "string";
    case "REAL":
      return "number";
    case "BLOB":
      return "ArrayBuffer";
  }
}

/**
 * Determine the TypeScript type for a column. A `checkRef` column becomes the
 * union of its lookup table's seeded primary-key values (when the seed
 * declares literal `rows` for that table); a numeric `range` stays the SQLite
 * base type.
 */
export function columnToTsType(
  col: ColumnDef,
  lookups?: Map<string, Record<string, unknown>[]>,
): string {
  const baseType = sqliteTypeToTs(col.sqliteType);
  let type = baseType;

  if (col.check?.kind === "ref") {
    const ref = col.check;
    const rows = lookups?.get(ref.table);
    if (rows && rows.length > 0) {
      const values = [
        ...new Set(rows.map((r) => r[ref.column]).filter((v) => v !== null && v !== undefined)),
      ];
      if (values.length > 0) {
        type = values
          .map((v) => (typeof v === "string" ? JSON.stringify(v) : String(v)))
          .join(" | ");
      }
    }
  }

  // PRIMARY KEY columns are never null.
  if (col.primaryKey) return type;

  // Columns without NOT NULL are nullable.
  if (!col.notNull) return `${type} | null`;

  return type;
}

function generateTableInterface(
  table: SchemaDef["tables"][number],
  overrides: Record<string, string>,
  lookups: Map<string, Record<string, unknown>[]>,
): string {
  const typeName = tableNameToTypeName(table.name, overrides);
  const lines = table.columns.map((col) => {
    const tsType = columnToTsType(col, lookups);
    return `  ${col.name}: ${tsType};`;
  });

  return `export interface ${typeName} {\n${lines.join("\n")}\n}`;
}

/**
 * Generate the full db-types.d.ts content from a SchemaDef.
 *
 * @param lookups Table name → literal seed rows, used to type `checkRef`
 *                columns as unions of the lookup's primary-key values.
 */
export function generateDbTypesContent(
  schema: SchemaDef,
  overrides: Record<string, string> = {},
  lookups: Map<string, Record<string, unknown>[]> = new Map(),
): string {
  const header = `/* AUTO-GENERATED by spindlework/fiber — do not edit */\n`;

  const interfaces = schema.tables
    .map((t) => generateTableInterface(t, overrides, lookups))
    .join("\n\n");

  const dbEntries = schema.tables
    .map((t) => `  ${t.name}: ${tableNameToTypeName(t.name, overrides)};`)
    .join("\n");
  const dbInterface = `export interface Database {\n${dbEntries}\n}`;

  const sqlModule = `declare module "*.sql" {\n  const sql: string;\n  export default sql;\n}`;

  return `${header}\n${interfaces}\n\n${dbInterface}\n\n${sqlModule}\n`;
}
