/**
 * Generate a runnable (additive/bootstrap) SQL script from a SchemaDef.
 *
 * The output uses `CREATE TABLE IF NOT EXISTS` / `CREATE INDEX IF NOT EXISTS`
 * so it is safe to run repeatedly against an existing database. It is a
 * *derived, convenience* output — the live-database reconciliation happens at
 * runtime via `applySchema()`, which is the authoritative update path.
 */

import type { SchemaDef } from "./schema";
import { renderCreateTable, renderCreateIndex } from "./ddl";

/** Generate the full schema.sql content for a SchemaDef. */
export function generateSchemaSqlContent(schema: SchemaDef): string {
  const header = [
    "-- AUTO-GENERATED by spindlework — do not edit",
    "-- Derived from src/domains/schema.ts",
    "",
  ].join("\n");

  const tableBlocks = schema.tables.map((t) => renderCreateTable(t, true));
  const indexBlocks = schema.indexes.map((i) => renderCreateIndex(i, true));

  const sections: string[] = [tableBlocks.join("\n\n")];
  if (indexBlocks.length > 0) {
    sections.push(`-- Indexes\n\n${indexBlocks.join("\n")}`);
  }

  return `${header}${sections.join("\n\n")}\n`;
}
