/**
 * Serialize a SchemaDef to a standalone TypeScript data module.
 *
 * The generated file is a pure data literal (no framework runtime imports in
 * the emitted JS) that the Worker imports and hands to applySchema(). Types
 * are preserved via a type-only import of SchemaDef.
 */

import type { SchemaDef } from "./schema";
import { generateSchemaSqlContent } from "./generate-sql";

/**
 * Convert a SchemaDef to a TS source file with a typed data literal.
 *
 * Roughly:
 *   import type { SchemaDef } from "js-mvc/schema";
 *   export const schemaDef: SchemaDef = { ... };
 */
export function serializeSchemaDef(schema: SchemaDef): string {
  const json = JSON.stringify(schema, null, 2);
  const header = `// AUTO-GENERATED by spindlework/fiber — do not edit\n// Source of truth: src/domains/schema.ts\n\n`;
  return `${header}import type { SchemaDef } from "spindlework/fiber";\n\nexport const schemaDef: SchemaDef = ${json};\n`;
}

/** Derive the additive bootstrap schema.sql content for a SchemaDef. */
export function serializeSchemaSql(schema: SchemaDef): string {
  return generateSchemaSqlContent(schema);
}
